# Practica 3

In [14]:
# Importamos las librerias necesarias para poder depurar el dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

%matplotlib inline

In [15]:
pokemons = pd.read_csv('./DatasetsLab1/pokemon.csv', encoding='latin-1')
pokemons

,PokÃ©mon,Tipo,PS,Ataque,Defensa,Ataque especial,Defensa especial,Velocidad
0,TYPHLOSION,Fuego,2,3,2,4,2,4
1,PONYTA,Fuego,2,3,2,2,2,3
2,TORKOAL,Fuego,2,3,4,3,2,1
3,ARCANINE,Fuego,3,5,3,4,3,4
4,STARMIE,Agua,2,3,3,4,2,4
5,PALKIA,Agua,3,4,3,5,3,4
6,MILOTIC,Agua,3,2,2,4,3,3
7,AZUMARILL,Agua,3,2,2,2,2,2
8,LEAFEON,Planta,2,4,4,2,2,3
9,ABOMASNOW,Planta,3,3,2,3,2,2
10,CHERUBI,Planta,1,1,2,2,1,1
11,BRELOOM,Planta,2,4,2,2,2,3
12,JOLTEON,ElÃ©ctrico,2,2,2,4,3,5
13,MAGNEZONE,ElÃ©ctrico,2,3,3,5,2,2
14,PIKACHU,ElÃ©ctrico,1,2,1,2,1,3
15,AMPHAROS,ElÃ©ctrico,3,3,3,5,4,3
16,DUSKNOIR,Fantasma,1,3,4,2,4,2
17,JIRATINA,Fantasma,4,4,3,4,3,3
18,SPIRITOMB,Fantasma,2,3,3,3,3,1
19,GENGAR,Fantasma,2,2,2,5,2,4

# Normalizamos el Dataset (Apartado A)

In [18]:
numeric_cols = ['PS', 'Ataque', 'Defensa', 'Ataque especial', 'Defensa especial', 'Velocidad']
X = pokemons[numeric_cols]

# Crear una instancia de StandardScaler
scaler = StandardScaler()

# Ajustar el scaler a los datos
scaler.fit(X)

# Transformar los datos utilizando el scaler ajustado
X_transformed = scaler.transform(X)

# Reemplazar las columnas numéricas en el DataFrame original con los datos transformados
pokemons[numeric_cols] = X_transformed

# Ver los datos transformados
pokemons

,PokÃ©mon,Tipo,PS,Ataque,Defensa,Ataque especial,Defensa especial,Velocidad
0,TYPHLOSION,Fuego,-0.326164,0.054313,-0.75,0.564152,-0.50,1.037975
1,PONYTA,Fuego,-0.326164,0.054313,-0.75,-1.171700,-0.50,0.135388
2,TORKOAL,Fuego,-0.326164,0.054313,1.75,-0.303774,-0.50,-1.669787
3,ARCANINE,Fuego,0.978492,2.226814,0.50,0.564152,0.75,1.037975
4,STARMIE,Agua,-0.326164,0.054313,0.50,0.564152,-0.50,1.037975
5,PALKIA,Agua,0.978492,1.140563,0.50,1.432078,0.75,1.037975
6,MILOTIC,Agua,0.978492,-1.031938,-0.75,0.564152,0.75,0.135388
7,AZUMARILL,Agua,0.978492,-1.031938,-0.75,-1.171700,-0.50,-0.767199
8,LEAFEON,Planta,-0.326164,1.140563,1.75,-1.171700,-0.50,0.135388
9,ABOMASNOW,Planta,0.978492,0.054313,-0.75,-0.303774,-0.50,-0.767199
10,CHERUBI,Planta,-1.630820,-2.118189,-0.75,-1.171700,-1.75,-1.669787
11,BRELOOM,Planta,-0.326164,1.140563,-0.75,-1.171700,-0.50,0.135388
12,JOLTEON,ElÃ©ctrico,-0.326164,-1.031938,-0.75,0.564152,0.75,1.940563
13,MAGNEZONE,ElÃ©ctrico,-0.326164,0.054313,0.50,1.432078,-0.50,-0.767199
14,PIKACHU,ElÃ©ctrico,-1.630820,-1.031938,-2.00,-1.171700,-1.75,0.135388
15,AMPHAROS,ElÃ©ctrico,0.978492,0.054313,0.50,1.432078,2.00,0.135388
16,DUSKNOIR,Fantasma,-1.630820,0.054313,1.75,-1.171700,2.00,-0.767199
17,JIRATINA,Fantasma,2.283148,1.140563,0.50,0.564152,0.75,0.135388
18,SPIRITOMB,Fantasma,-0.326164,0.054313,0.50,-0.303774,0.75,-1.669787
19,GENGAR,Fantasma,-0.326164,-1.031938,-0.75,1.432078,-0.50,1.037975

### Calculamos los autovalores y autovectores a partir de la matriz de covarianza

In [24]:
cov_matrix = np.cov(X_transformed.T)
cov_matrix

array([[ 1.05263158,  0.46617892,  0.08583264,  0.49167616,  0.42916321,
         0.23241437],
       [ 0.46617892,  1.05263158,  0.54312545,  0.16622796,  0.38590492,
         0.25026927],
       [ 0.08583264,  0.54312545,  1.05263158,  0.10278072,  0.50986842,
        -0.24939914],
       [ 0.49167616,  0.16622796,  0.10278072,  1.05263158,  0.41112288,
         0.49682728],
       [ 0.42916321,  0.38590492,  0.50986842,  0.41112288,  1.05263158,
         0.19001839],
       [ 0.23241437,  0.25026927, -0.24939914,  0.49682728,  0.19001839,
         1.05263158]])

In [25]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

In [22]:
print("Autovalores: ", eigenvalues)
print("Autovectores: ", eigenvectors)

Autovalores:  [2.62997944 1.55066147 0.16420572 0.47459774 0.71552145 0.78082366]
Autovectores:  [[ 0.45454125  0.15847313  0.37672419 -0.07820604  0.78451794  0.06908557]
 [ 0.45072878 -0.25198079 -0.491921    0.1067326  -0.02435867  0.69237113]
 [ 0.31882326 -0.63200759  0.5475605   0.33202671 -0.277256   -0.10946693]
 [ 0.42331653  0.38227978 -0.30437481  0.61163075 -0.07575687 -0.4496554 ]
 [ 0.48098891 -0.16852151 -0.23006595 -0.68447289 -0.16380914 -0.43815894]
 [ 0.27935701  0.58087953  0.41315342 -0.17220602 -0.52392254  0.33119957]]

### Obtenemos un dataframe con estos datos

In [23]:
sorted_idx = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_idx]

In [26]:
explained_variance_ratio = sorted_eigenvalues / sum(sorted_eigenvalues)
cumulative_variance_ratio = np.cumsum(explained_variance_ratio)

In [27]:
variance_df = pd.DataFrame({'Componente': range(1, len(eigenvalues)+1),
                            'Porcentaje de Varianza': explained_variance_ratio*100,
                            'Porcentaje Acumulado de Varianza': cumulative_variance_ratio*100})

In [28]:
variance_df

   Componente  Porcentaje de Varianza  Porcentaje Acumulado de Varianza
0           1               41.641341                         41.641341
1           2               24.552140                         66.193481
2           3               12.363041                         78.556522
3           4               11.329090                         89.885612
4           5                7.514464                         97.400076
5           6                2.599924                        100.000000